<a href="https://colab.research.google.com/github/21130407KhuongVo/MachineLearning/blob/main/Lab1_21130407.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
L = [1, 2, 3, 6, 9, 4, 5, 10, 18, 12, 15, 13, 17]


def find(L, max=True):
    result: int = L[1]
    if (max):
        for i in L:
            if i > result: result = i
    else:
        for i in L:
            if i < result: result = i
    return result

def sort(L):
    n = len(L)
    for i in range(n):
        for j in range(i + 1, n):
            if L[i] > L[j]:
                L[i], L[j] = L[j], L[i]

    return L

def count(L):
    positive = 0
    negative = 0
    for i in L:
        if (i > 0):
            positive += 1
        else:
            negative += 1
    print('Positive: ', positive, '\tNegative: ', negative)


print(find(L,False)) # find min
print(find(L)) # find max
print(sort(L)) # sort the list L in ascending order
count(L) # show how many positive and negative numbers are in the list L


1
18
[1, 2, 3, 4, 5, 6, 9, 10, 12, 13, 15, 17, 18]
Positive:  13 	Negative:  0


In [ ]:
def comput(n):
    result:float=0
    for i in range(1,n+1):
        result+=factorial(i)
    return result
def factorial(n):
    result:float =1
    while n>1:
        result*=n
        n-=1
    return result

print(comput(3))


9


In [1]:
from datetime import datetime


class Account:
    def __init__(self, name, email, country, friends, posts):
        self.name = name
        self.email = email
        self.country = country
        self.friends = friends or []
        self.posts = posts or []

    def getMaxLikePostByFriend(self):
        if not self.friends:  # Check if friends list is empty
            return None  # Return None gracefully

        # Iterate through friends and find the friend with the post having the most likes
        best_friend = None
        best_post_likes = 0
        for friend in self.friends:
            # Access the friend's posts and find their post with the most likes
            friend_best_post = friend.getMaxLikePost()
            if friend_best_post and friend_best_post.likes > best_post_likes:
                best_friend = friend
                best_post_likes = friend_best_post.likes

        return best_friend

    def getMaxLikePost(self):
        if not self.posts:  # Check if posts list is empty
            return None  # Return None gracefully

        result = self.posts[0]
        for post in self.posts:
            if post.likes > result.likes:
                result = post
        return result

    def __str__(self):
        return f"Name: {self.name}\nEmail: {self.email}\""

    def verifyAccount(self):
        return VerifiedAccount(self, datetime.now())

class AccountManager:
    def __init__(self, accounts):
        self.accounts = accounts

    def groupAccountsByPostLike(self):
        accounts_by_post_count = {}
        for account in self.accounts:
            key = True if len(account.posts) >= 10 else False
            accounts_by_post_count.setdefault(key, []).append(account)

        return accounts_by_post_count

    def filterAccounts(self, country: str):
        result = set()
        for account in self.accounts:
            if account.country == country:
                result.add(account)
        return result


class Post:
    def __init__(self, content: str = 'This is content', subject: str = 'Title', likes: int = 0):
        self.content = content
        self.subject = subject
        self.likes = likes


class VerifiedAccount(Account):
    def __init__(self, account, fromDate: datetime):
        self.fromDate = fromDate
        super().__init__(account.name, account.email, account.country, account.friends, account.posts)

    def __str__(self):
        return f'Name: {self.name}\tEmail: {self.email}\tVerifyDate: {self.fromDate}'


# 10 đối tượng Post với giá trị likes ngẫu nhiên
post1 = Post("Bài đăng 1", "Chủ đề 1", 10)
post2 = Post("Bài đăng 2", "Chủ đề 2", 11)
post3 = Post("Bài đăng 3", "Chủ đề 3", 12)
post4 = Post("Bài đăng 4", "Chủ đề 4", 13)
post5 = Post("Bài đăng 5", "Chủ đề 5", 14)
post6 = Post("Bài đăng 6", "Chủ đề 6", 15)
post7 = Post("Bài đăng 7", "Chủ đề 7", 16)
post8 = Post("Bài đăng 8", "Chủ đề 8", 17)
post9 = Post("Bài đăng 9", "Chủ đề 9", 18)
post10 = Post("Bài đăng 10", "Chủ đề 10", 19)
# Sử dụng các đối tượng Post sau này...
acc1 = Account('Vo Nguyen Nhat Khuong', '21130407@st.hcmuaf.edu.vn', 'Vietnam', None,
               [post1, post2, post3, post4, post5])
acc2 = Account('Le Phi Long', '21130436@st.hcmuaf.edu', 'Vietnam', None,
               [post6, post9])
acc3 = Account('Nguyen Thi Thuy Thuy', '21130560@st.hcmuaf.edu.vn', 'Vietnam', None,
               [post7, post8, post10])
acc1.friends.append(acc2)
acc1.friends.append(acc3)
acc2.friends.append(acc1)
acc2.friends.append(acc3)
acc3.friends.append(acc2)
acc3.friends.append(acc1)
manager = AccountManager([acc1, acc2, acc3])
print(acc1.getMaxLikePostByFriend())
print(manager.groupAccountsByPostLike())
print(manager.filterAccounts('Vietnam'))
ver1 = acc1.verifyAccount()
print(ver1)

Name: Nguyen Thi Thuy Thuy
Email: 21130560@st.hcmuaf.edu.vn"
{False: [<__main__.Account object at 0x7d3b9857bdf0>, <__main__.Account object at 0x7d3b9857be80>, <__main__.Account object at 0x7d3b9857bee0>]}
{<__main__.Account object at 0x7d3b9857be80>, <__main__.Account object at 0x7d3b9857bee0>, <__main__.Account object at 0x7d3b9857bdf0>}
Name: Vo Nguyen Nhat Khuong	Email: 21130407@st.hcmuaf.edu.vn	VerifyDate: 2024-03-06 08:39:42.156504


In [2]:
import numpy as np


# task 2.1
def task2_1():
    # create
    array = np.arange(10, 26)

    # reverser
    reversed_array = array[::-1]

    print(reversed_array)


# task 2.2
def task2_2(arr_inp, repeat):
    repeat_arr = np.tile(arr_inp, repeat)
    print(repeat_arr)


# task 2.3
def task2_3(arr_inp):
    arr_inp[arr_inp > 0.5] = 0.5
    print(arr_inp)


task2_1()
task2_2([1,2,3], 3)
task2_3(np.array([
    [0.42, 0.48, 0.32],
    [0.74, 0.58, 0.38],
    [0.51, 0.34, 0.15]
]))

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[1 2 3 1 2 3 1 2 3]
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
